### PR TITLE
Updated Anime Plugin to work with current version of Emby

### PR DESCRIPTION
**Pull request by mtlott**
- Fixed Null Reference to series.People causing crashes
- Added support for MissingEpisodes
- Added support for GetSearchResults during identify operation

### CODE REVIEW

**Comment by TomGillen** [comment]
Thanks for this, I'll take a proper look at it later today.

**Comment by CtrlAltDefeat94** [comment]
Any updates?

**Comment by TomGillen** [comment]
I had totally forgotten about this! I'll take a look at it now.

**Comment by TomGillen** [comment]
Are you still working on this, or shall I merge it?

**Comment by mtlott** [comment]
I am trying to get image fetching in identify to work right. But I suspect that there is a more basic problem somewhere else. I did add another commit for auto-organize to work. If you got that you should merge and push it out for now. I think people are getting anxious :-)

**Comment by TomGillen** [comment]
Merged and released. Thanks for that!

**Pull request merged**
